services:
    mbh.room.cache.generator:
        class: MBH\Bundle\PackageBundle\Services\RoomCacheGenerator
        arguments: [@service_container]
        
    mbh.package.search:
        class: MBH\Bundle\PackageBundle\Services\Search
        arguments: [@service_container]

    mbh.tourists.messenger:
            class: MBH\Bundle\PackageBundle\Services\TouristsMessenger
            arguments: [@service_container]
        
    mbh.calculation:
        class: MBH\Bundle\PackageBundle\Services\Calculation
        arguments: [@service_container]

    mbh.order:
            class: MBH\Bundle\PackageBundle\Services\Order
            arguments: [@service_container]

    mbh.package.permissions:
            class: MBH\Bundle\PackageBundle\Services\Permissions
            arguments: [@service_container]

    mbh.package.subscriber:
        class: MBH\Bundle\PackageBundle\EventListener\PackageSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}

    mbh.package.order.subscriber:
            class: MBH\Bundle\PackageBundle\EventListener\OrderSubscriber
            arguments: [@service_container]
            tags:
                - { name: doctrine_mongodb.odm.event_subscriber, connection: default}
            
    mbh.package.validator:
            class: MBH\Bundle\PackageBundle\Validator\Constraints\PackageValidator
            arguments: [@service_container]
            tags:
                - { name: validator.constraint_validator, alias: mbh.package.validator }