# Значения справочника см. в каталоге DOC\Справочники\ файл dict_s_docum.csv.
docum:
  vega_residence: 'ВИД НА ЖИТЕЛЬСТВО ИГ'
  vega_visa: 'ВИЗА'
  vega_military_spare: 'ВОЕННЫЙ БИЛЕТ ОФИЦЕРА ЗАПАСА'
  vega_temporary_identity: 'ВРЕМЕННОЕ УДОСТОВЕРЕНИЕ ЛИЧНОСТИ'
  vega_diplomatic_passport: 'ДИПЛОМАТИЧЕСКИЙ ПАСПОРТ'
  vega_travel_passport: 'ЗАГРАН. ПАСПОРТ'
  vega_russian_passport: 'ПАСПОРТ РФ'
  vega_ussr_passports: 'ПАСПОРТ СССР'
  vega_passport_IG: 'ПАСПОРТ ИГ'
  vega_seaman: 'ПАСПОРТ МОРЯКА'
  vega_temporary_residence permit_IG: 'РАЗРЕШЕНИЕ НА ВРЕМЕННОЕ ПРОЖИВАНИЕ ИГ'
  vega_predost_temporate_asylum: 'СВ-ВО О ПРЕДОСТ. ВРЕМЕННОГО УБЕЖИЩА'
  vega_refugee: 'СВ-ВО О РАССМ. ХОД-ВА О ПРИЗН. БЕЖЕНЦЕМ'
  vega_birth_certificate: 'СВИДЕТЕЛЬСТВО О РОЖДЕНИИ'
  vega_st_of_birth_ig: 'СВ-ВО О РОЖДЕНИИ ИГ'
  vega_service_passports: 'СЛУЖЕБНЫЙ ПАСПОРТ'
  vega_refugee_certificate: 'УДОСТОВЕРЕНИЕ БЕЖЕНЦА'
  vega_id_card_person_of_military: 'УДОСТОВ. ЛИЧНОСТИ ВОЕННОСЛУЖАЩЕГО'
  vega_residence_permit_stateless_persons: 'ВИД НА ЖИТЕЛЬСТВО ЛБГ'
  vega_military_id_soldier: 'ВОЕННЫЙ БИЛЕТ СОЛДАТА'
  vega_travel_passport biometrics: 'ЗАГРАН. ПАСПОРТ НОВОГО ПОКОЛЕНИЯ (С БИОМЕТРИЕЙ)'
  vega_temporary_residence permit stateless persons: 'РАЗРЕШЕНИЕ НА ВРЕМЕННОЕ ПРОЖИВАНИЕ ЛБГ'
  vega_migration_cart: 'МИГРАЦИОННАЯ КАРТА'
  vega_ig_arrival_notice:  'УВЕДОМЛЕНИЕ О ПРИБЫТИИ ИГ/ЛБГ В МЕСТО ПРЕБЫВАНИЯ'
  vega_return_certificate: 'СВИДЕТЕЛЬСТВО НА ВОЗВРАЩЕНИЕ'
  vega_non_citizen_passport: 'ПАСПОРТ НЕГРАЖДАНИНА'
  vega_national_id_republic_of_kazakhstan': 'УДОСТОВЕРЕНИЕ ЛИЧНОСТИ ГРАЖДАНИНА РЕСПУБЛИКИ КАЗАХСТАН'