docum:
  - 'ВИД НА ЖИТЕЛЬСТВО ИГ'
  - 'ВИЗА'
  - 'ВОЕННЫЙ БИЛЕТ ОФИЦЕРА ЗАПАСА'
  - 'ВРЕМЕННОЕ УДОСТОВЕРЕНИЕ ЛИЧНОСТИ'
  - 'ДИПЛОМАТИЧЕСКИЙ ПАСПОРТ'
  - 'ЗАГРАН. ПАСПОРТ'
  - 'ПАСПОРТ РФ'
  - 'ПАСПОРТ СССР'
  - 'ПАСПОРТ ИГ'
  - 'ПАСПОРТ МОРЯКА'
  - 'РАЗРЕШЕНИЕ НА ВРЕМЕННОЕ ПРОЖИВАНИЕ ИГ'
  - 'СВ-ВО О ПРЕДОСТ. ВРЕМЕННОГО УБЕЖИЩА'
  - 'СВ-ВО О РАССМ. ХОД-ВА О ПРИЗН. БЕЖЕНЦЕМ'
  - 'СВИДЕТЕЛЬСТВО О РОЖДЕНИИ'
  - 'СВ-ВО О РОЖДЕНИИ ИГ'
  - 'СЛУЖЕБНЫЙ ПАСПОРТ'
  - 'УДОСТОВЕРЕНИЕ БЕЖЕНЦА'
  - 'УДОСТОВ. ЛИЧНОСТИ ВОЕННОСЛУЖАЩЕГО'
  - 'ВИД НА ЖИТЕЛЬСТВО ЛБГ'
  - 'ВОЕННЫЙ БИЛЕТ СОЛДАТА'
  - 'ЗАГРАН. ПАСПОРТ НОВОГО ПОКОЛЕНИЯ (С БИОМЕТРИЕЙ)'
  - 'РАЗРЕШЕНИЕ НА ВРЕМЕННОЕ ПРОЖИВАНИЕ ЛБГ'
  - 'МИГРАЦИОННАЯ КАРТА'
  - 'УВЕДОМЛЕНИЕ О ПРИБЫТИИ ИГ/ЛБГ В МЕСТО ПРЕБЫВАНИЯ'
  - 'СВИДЕТЕЛЬСТВО НА ВОЗВРАЩЕНИЕ'
  - 'ПАСПОРТ НЕГРАЖДАНИНА'
  - 'УДОСТОВЕРЕНИЕ ЛИЧНОСТИ ГРАЖДАНИНА РЕСПУБЛИКИ КАЗАХСТАН'