tpscan:
  notify_front: 'УВЕДОМЛЕНИЕ - ЛИЦЕВАЯ СТОРОНА'
  notify_back: 'УВЕДОМЛЕНИЕ - ОБОРОТНАЯ СТОРОНА'
  docuemnt: 'ДОКУМЕНТ'
  visa: 'ВИЗА'
  residence_ig: 'ВИД НА ЖИТЕЛЬСТВО ИГ'
  residence_lbg: 'ВИД НА ЖИТЕЛЬСТВО ЛБГ'
  temporary_accommodation_ig: 'РАЗРЕШЕНИЕ НА ВРЕМЕННОЕ ПРОЖИВАНИЕ ИГ'
  temporary_accommodation_lbg: 'РАЗРЕШЕНИЕ НА ВРЕМЕННОЕ ПРОЖИВАНИЕ ЛБГ'
  migration_card: 'МИГРАЦИОННАЯ КАРТА'
