services:
    mbh.cash.document.subscriber:
        class: MBH\Bundle\CashBundle\EventListener\CashDocumentSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}
    mbh.cash.1c_exporter:
        class: MBH\Bundle\CashBundle\Service\OneCExporter
        arguments: [@service_container]

    mbh.cash:
        class: MBH\Bundle\CashBundle\Service\Cash
        arguments: [@service_container]