services:
    mbh.package.subscriber:
        class: MBH\Bundle\CashBundle\EventListener\CashDocumentSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}