services:
    security.authentication.success_handler:
        class: MBH\Bundle\UserBundle\Security\AuthenticationSuccessHandler
        arguments:  ["@security.http_utils", {}, "@mbh.mbhs"]
        tags:
            - { name: 'monolog.logger', channel: 'security' }