services:
    mbh.mbhs:
        class: MBH\Bundle\ClientBundle\Service\Mbhs
        arguments: ['@service_container']
    mbh.notice.unpaid:
        class: MBH\Bundle\ClientBundle\Service\NoticeUnpaid
        arguments: ['@service_container','@doctrine_mongodb', '@mbh.notifier.mailer']
        
    #Dashboard
    mbh.dashboard:
      class: MBH\Bundle\ClientBundle\Service\Dashboard\Dashboard
      calls:
        - [attach, ["@mbh.dashboard.room_cache"]]
      arguments: ['@doctrine_mongodb']

    mbh.dashboard.room_cache:
      class: MBH\Bundle\ClientBundle\Service\Dashboard\RoomCacheSource
      arguments: ['@doctrine_mongodb', '@validator']

    mbh_bundle_client.twig.dashboard_extension:
        class: MBH\Bundle\ClientBundle\Twig\DashboardExtension
        arguments: ['@mbh.dashboard']
        tags:
            - { name: twig.extension }
