services:
    mbh.mbhs:
        class: MBH\Bundle\ClientBundle\Service\Mbhs
        arguments: ['@service_container']
    mbh.notice.unpaid:
        class: MBH\Bundle\ClientBundle\Service\NoticeUnpaid
        arguments: ['@service_container','@doctrine_mongodb', '@mbh.notifier.mailer']

    mbh_package_zip:
          class: MBH\Bundle\ClientBundle\Service\PackageZip
          arguments:
              - '@doctrine.odm.mongodb.document_manager'
              - '@service_container'
              - '@validator'
              - '@mbh.package_zip.logger'
              - '@mbh.order_manager'
              - '@mbh.package.search'
              - '@mbh.helper'

    mbh.package_zip.logger:
          class:     Symfony\Bridge\Monolog\Logger
          arguments: [app]
          calls:
              - [pushHandler, ['@mbh.package_zip.logger_handler']]

    mbh.package_zip.logger_handler:
          class:     Monolog\Handler\StreamHandler
          arguments: [%kernel.logs_dir%/%kernel.environment%.packageZip.log, 200]
