services:
    mbh.mbhs:
        class: MBH\Bundle\ClientBundle\Service\Mbhs
        arguments: ['@service_container']
    mbh.notice:
        class: MBH\Bundle\ClientBundle\Service\Notice
        arguments: ['@service_container']