services:
    mbh.mbhs:
        class: MBH\Bundle\ClientBundle\Service\Mbhs
        arguments: ['@service_container']
    mbh.notice.unpaid:
        class: MBH\Bundle\ClientBundle\Service\NoticeUnpaid
        arguments: ['@doctrine_mongodb', '@mbh.notifier.mailer']