imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: version.yml }
    - { resource: mbh.yml }
    - { resource: roles.yml }
    - { resource: mbh_restaurant_ctypes.xml }

framework:
    serializer:
        enabled: true
    #esi:             ~
    translator:      { fallback: ["%locale%", ru, en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: false
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    trusted_proxies:  [127.0.0.1, 127.0.1.1, 176.192.20.30]

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    base_template_class: MBH\Bundle\BaseBundle\Twig\Template
    globals:
        recaptcha: "%mbh.recaptcha%"
        meta_title: 'Система бронирования "MaxiBooking".'
        project_title: 'MaxiBooking'
        months:
          1: 'Январь'
          2: 'Февраль'
          3: 'Март'
          4: 'Апрель'
          5: 'Май'
          6: 'Июнь'
          7: 'Июль'
          8: 'Август'
          9: 'Сентябрь'
          10: 'Октябрь'
          11: 'Ноябрь'
          12: 'Декабрь'
        weekdays:
          1: 'Пн'
          2: 'Вт'
          3: 'Ср'
          4: 'Чт'
          5: 'Пт'
          6: 'Сб'
          7: 'Вс'
        environment: "%mbh.environment%"
        version: "%mbh.version%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: '%use_assetic_controller%'
    filters:
        cssrewrite: ~
        uglifycss:
            bin: /usr/local/bin/uglifycss
            node: /usr/bin/nodejs
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
            node: /usr/bin/nodejs
        less:
            node: /usr/bin/nodejs
            node_paths: [/usr/local/lib/node_modules/]
            apply_to: "\.less$"
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: file }
    encryption: ssl
    
# DoctrineMongoDBBundle Configuration
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_url%
            options: {}
    default_database: %mongodb_database%
    document_managers:
        default:
            connection: 'default'
            auto_mapping: true
            filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\ODM\SoftDeleteableFilter
                        enabled: true
                    hotelable:
                        class: MBH\Bundle\BaseBundle\Filter\HotelableFilter
                        enabled: false
            mappings:
                gedmo_loggable:
                    type: annotation
                    prefix: Gedmo\Loggable\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Document"
                    alias: GedmoLoggable # this one is optional and will default to the name set for the mapping
                    is_bundle: false
                gedmo_translatable:
                    type: annotation
                    prefix: Gedmo\Translatable\Document
                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Document"
                    alias: GedmoTranslatable # this one is optional and will default to the name set for the mapping
                    is_bundle: false
#                gedmo_translator:
#                    type: annotation
#                    prefix: Gedmo\Translator\Document
#                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Document"
#                    alias: GedmoTranslator # this one is optional and will default to the name set for the mapping
#                    is_bundle: false
#                gedmo_tree:
#                    type: annotation
#                    prefix: Gedmo\Tree\Document
#                    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Document"
#                    alias: GedmoTree # this one is optional and will default to the name set for the mapping
#                    is_bundle: false

# StofDoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    # see /src/MBH/Bundle/BaseBundle/Resources/config/doctrine_extensions.yml
    default_locale: ru_RU
    translation_fallback: true
    mongodb:
        default:
            blameable:      true
            timestampable:  true
            loggable:       true
            softdeleteable: true
            sluggable:      false
            translatable:   true
            uploadable:     false
            tree:           false
            sortable:       false
            
# FOSUserBundle Configuration
fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: MBH\Bundle\UserBundle\Document\User
    group:
            group_class: MBH\Bundle\UserBundle\Document\Group
    
# KnpMenuBundle Configuration    
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: MBHBaseBundle:Menu:menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig

# KnpSnappyBundle Configuration
knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/h
        options:    []

# IamPersistentMongoDBAclBundle Configuration
iam_persistent_mongo_db_acl:
    acl_provider:
        default_database: %mongodb_database%

liip_imagine:
    resolvers:
        default:
            web_path: ~
    loaders:
        protected:
            filesystem:
                data_root: %kernel.root_dir%/../protectedUpload
    filter_sets:
        cache: ~
        thumb_100x100:
            quality: 100
            filters:
                thumbnail: { size: [100, 100], mode: outbound, allow_upscale: true }
        thumb_130x110:
            quality: 100
            filters:
              thumbnail: { size: [130, 110], mode: outbound, allow_upscale: true }
        thumb_95x80:
            quality: 100
            filters:
              thumbnail: { size: [95, 80], mode: outbound, allow_upscale: true }

        stamp:
            data_loader: protected
            quality: 100
            filters:
              thumbnail: { size: [10, 10], mode: outbound, allow_upscale: true }


        scaler:
            quality: 100
            filters:
              relative_resize: { scale: 0.5, allow_upscale: true }


jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            excluded_dirs: [%kernel.root_dir%/../var/cache, %kernel.root_dir%/../var/logs]
            excluded_names: ["*TestCase.php", "*Test.php"]

# GravatarBundle
ornicar_gravatar:
  rating: g
  size: 160
  default: mm

# KNPMenu
parameters:
    knp_menu.renderer.twig.options:
        currentClass: active

#
bazinga_js_translation:
    default_domain: messages
    locale_fallback: ru

fos_rest:
    body_listener: true
    view:
      view_response_listener: true
    serializer:
        serialize_null: true
    body_converter:
        enabled: true
    format_listener:
        rules:
            - { path: '^/api',  priorities: ['json'], fallback_format: json, prefer_extension: true }