imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

swiftmailer:
    disable_delivery: true

parameters:
    mongodb_url: 'mongodb://mbh-mongo:27017/db_test'
    mongodb_database: db_test

security:
    firewalls:
        main:
            http_basic: ~
            form_login: false
            remember_me: false