parameters:
    #organization info
    mbh.organization:
      title: 'OOO "Название предприятия"'
      position: 'Директор OOO "Название предприятия"'
      name: 'Иванов И.В.'

    #mailer
    mbh.mailer:
      from: {'robot@maxi-booking.ru': 'MaxiBooking'}
      subject: 'Сообщение от MaxiBooking'
      template: 'MBHBaseBundle:Mailer:base.html.twig'

    #генерация кеша
    mbh.room.cache.message: <i class="fa fa-spinner fa-spin"></i> Внимание! Идет пересчет цен и количества свободных номеров.
    mbh.room.cache.message.type: danger

    #параметры онлайн формы
    mbh.online.form:
          sites: ['http://test.h', 'http://test2.h']
          packages_max: 5
          messages: true
          form:
            width: '300px'
            height: 'auto'
          result:
            width: 'auto'
            height: 'auto'
            url: '/demo/results.html'
          payment_types:
            in_hotel: 'Оплата при заселении'
            online_full: 'Предварительная оплата'
            online_first_day: 'Предварительная оплата первого дня'

    #параметры Channel manager
    mbh.channelmanager.services:
        vashotel:
          title: 'ВашОтель.RU'
          service: 'mbh.channelmanager.vashotel'
          fee: 0.15
        #booking: {title: 'Booking.com', service: 'mbh.channelmanager.booking'}

    #параметры логов
    mbh.logs.max: 100

    #параметры отчетов
    mbh.reports.accommodation.rooms.max: 15

    #Типы отчетов аналитики
    mbh.analytics.types:
        sales_packages: "Динамика продаж по количеству броней"
        sales_cash: "Динамика продаж по стоимости броней"

    #Цели приезда
    mbh.package.arrivals:
        tourism: "Отдых/туризм"
        work: "Работа/стажировка"
        study: "Курсы/учеба"
        residence: "Временное проживание"
        other: "Другое"

    #Время заезда по умолчанию
    mbh.package.arrival.time: 12
    
    #Цели приезда
    mbh.package.statuses:
        offline: { title: "Обычная", class: "info"}
        online: { title: "Онлайн", class: "success"}
        channel_manager: { title: "Channel manager", class: "danger"}

    #Виды способов оплаты
    mbh.cash.methods:
        cash: "Наличные"
        cashless: "Безнал"
        electronic: "Электронный"
    
    #Типы операций с кассой
    mbh.cash.operations:
        in: "Поступление"
        out: "Возврат"
        #fine: "Штраф"
        fee: "Комиссия"
            
    #Типы питания
    mbh.food.types:
        RO:  "Без питания"
        BB:  "Завтрак"
        HB:  "Завтрак и ужин"
        FB:  "Завтрак, обед и ужин"
        AI:  "Все включено"
        UAI: "Ультра все включено"
        
    #Типы рассчета
    mbh.calculation.types:
        perRoom:      "Цена за номер"
        customPrices: "Цена за человека"
        
    #Типы тарифов
    mbh.tariff.types:
        rate:      "Процент от цен основного тарифа"
        price:     "Индивидуальные цены"

    #М/Ж
    mbh.gender.types:
        male: "Мужчина"
        female: "Женщина"
        unknown: "Неизвестно"

    
    