parameters:
    #генерация кеша
    mbh.room.cache.message: <i class="fa fa-spinner fa-spin"></i> Внимание! Идет пересчет цен и количества свободных номеров.
    mbh.room.cache.message.type: danger

    #параметры онлайн формы
    mbh.online.form:
          sites: ['http://test.h', 'http://test2.h']
          packages_max: 5
          form:
            width: '300px'
            height: 'auto'
          result:
            width: 'auto'
            height: 'auto'
            url: 'http://test.h/hotel/results.html'

    #параметры Channel manager
    mbh.channelmanager.services:
        vashotel:
          title: 'ВашОтель.RU'
          service: 'mbh.channelmanager.vashotel'
          fee: 0.15
        #booking: {title: 'Booking.com', service: 'mbh.channelmanager.booking'}

    #параметры логов
    mbh.logs.max: 100

    #параметры отчетов
    mbh.reports.accommodation.rooms.max: 15

    #Типы отчетов аналитики
    mbh.analytics.types:
        sales_packages: "Динамика продаж по количеству броней"
        sales_cash: "Динамика продаж по стоимости броней"

    #Цели приезда
    mbh.package.arrivals:
        tourism: "Отдых/туризм"
        work: "Работа/стажировка"
        study: "Курсы/учеба"
        residence: "Временное проживание"
        other: "Другое"
    
    #Цели приезда
    mbh.package.statuses:
        offline: { title: "Обычная", class: "info"}
        online: { title: "Онлайн", class: "success"}
        channel_manager: { title: "Channel manager", class: "danger"}

    #Виды способов оплаты
    mbh.cash.methods:
        cash: "Наличные"
        cashless: "Безнал"
        electronic: "Электронный"
    
    #Типы операций с кассой
    mbh.cash.operations:
        in: "Поступление"
        out: "Возврат"
        fine: "Штраф"
        fee: "Комиссия"
            
    #Типы питания
    mbh.food.types:
        RO:  "RO - Без питания"
        BB:  "BB - Завтрак"
        HB:  "HB - Завтрак и ужин"
        FB:  "FB - Завтрак, обед и ужин"
        AI:  "AI - Все включено"
        UAI: "UAI - Ультра все включено"
        
    #Типы рассчета
    mbh.calculation.types:
        perRoom:      "Цена за номер"
        customPrices: "Ручные цены"
        
    #Типы тарифов
    mbh.tariff.types:
        rate:      "Процент от цен основного тарифа"
        price:     "Конкретные цены"

    #М/Ж
    mbh.gender.types:
        male: "Мужчина"
        female: "Женщина"
        unknown: "Неизвестно"

    
    