parameters:
    mbh.currency.ratio.fix: %currency_ratio_fix%

    #timezone. default - deafult server timezone
    mbh.timezone: "%mbh_timezone%"

    mbh.weekdays: {1: 'Понедельник', 2: 'Вторник', 3: 'Среда', 4: 'Четверг', 5: 'Пятница', 6: 'Суббота', 0: 'Воскресенье'}

    mbh.mongodb:
      url: "%mongodb_url%"
      db : "%mongodb_database%"

    mbh.environment: "%mbh_environment%"

    #mbh hotel config
    mbh.hotel:
      types:
        apartments: 'Апартаменты'
        recreation_center: 'База отдыха'
        guest_house: 'Гостевой дом'
        pension: 'Пансионат'
        sanatorium: 'Санаторий'
        country_club: 'Загородный клуб'
        hostel: 'Хостел'
        hotel: 'Отель'
        motel: 'Мотель'
        resort: 'Курортный отель'
        mini_hotel: 'Мини-отель'
      themes:
        сity_tour: 'Экскурсия по городу'
        budget_travel: 'Бюджетные и молодежные поездки'
        shoping: 'Шопинг'
        family_trip: 'Семейная поездка'
        international: 'Международный'
        business_trip: 'Деловая поездка'
        romantic_vacation: 'Романтический отпуск/Медовый месяц'
        interior_design: 'Дизайнерский интерьер'
        luxury_holidays: 'Отдых класса люкс'
        haute_cuisine: 'Изысканная кухня'
        country_holidays: 'Загородный отдых'
        homestead: 'Усадьба'
        nature: 'Природа/Дикая флора и фауна'
        spa: 'Спа/Оздоровительные процедуры'
        ecological: 'Экологический'
        ski: 'Горы/лыжи'
        adventure: 'Приключение'
        sport: 'Спорт'
        beach: 'Пляж/Побережье'
        city: 'Городской'
      facilities:
        parking: 'Парковка'
        animals: 'Разрешены животные'
        hour_front_desk: 'Круглосуточная стойка регистрации'
        fitness: 'Фитнес-центр'
        wi_fi: 'Wi-Fi'
        free_wi_fi: 'Бесплатный Wi-Fi'
        conditioner: 'Кондиционер'
        pool: 'Бассейн'
        bathroom: 'Ванная комната в номерах'
        breakfast: 'Завтрак включен'
        sauna: 'Баня/Сауна'
        car: 'Прокат автомобиля'

    #mbhs
    mbh.mbhs:
      mbhs: 'aHR0cDovL21iaHMubWF4aWJvb2tpbmcucnUv'
      key: '%mbhs_key%'

    #mbh sources
    mbh.default.sources: ['Он-лайн бронирование', 'ВашОтель.ру', 'Постоянный клиент', 'Рекомендация знакомых']

    #mbh task
    mbh.default.taskType: ['Задача_1', 'Задача_2', 'Задача_3', 'Задача_4']

    #mbh services
    mbh.services:
      calcTypes:
        per_stay: 'за весь срок'
        per_night: 'за cутки'
        not_applicable: 'за услугу'
        day_percent: 'за услугу (% от цены за сутки)'

    #mailer
    mbh.mailer:
      fromText: 'MaxiBooking'
      fromMail: robot@maxi-booking.ru
      subject: 'Сообщение от MaxiBooking'
      template: 'MBHBaseBundle:Mailer:base.html.twig'

    #генерация кеша
    mbh.room.cache.message: <i class="fa fa-spinner fa-spin"></i> Внимание! Идет пересчет цен и количества свободных номеров.
    mbh.room.cache.message.type: danger
    mbh.room.cache.date.modify: '-1 month'

    #параметры онлайн формы
    mbh.online.form:
          sites: %online_form_sites%
          packages_max: 5
          messages: true
          form:
            width: '300px'
            height: 'auto'
          result:
            width: 'auto'
            height: 'auto'
            url: %online_form_result_url%
          payment_types:
            in_hotel: 'Оплата при заселении'
            online_full: 'Онлайн оплата (100%)'
            online_first_day: 'Онлайн оплата (одни сутки)'
            online_half: 'Онлайн оплата (50%)'

    #платежные системы
    mbh.payment_systems:
      moneymail: 'MoneyMail'
      robokassa: 'Robokassa'
      payanyway: 'PayAnyWay'
    mbh.payment_systems.default: moneymail
    mbh.payment_systems.change: %mbh_payment_systems_change%

    #параметры Channel manager
    mbh.channelmanager.services:
        vashotel:
          title: 'ВашОтель.RU'
          service: 'mbh.channelmanager.vashotel'
          password: jguuE26t684Fl
        booking:
          title: 'Booking.com'
          service: 'mbh.channelmanager.booking'
          username: maxibookingXML
          password: bMBhv6tds5i


    #параметры логов
    mbh.logs.max: 100

    #параметры отчетов
    mbh.reports.accommodation.rooms.max: 15

    #Типы отчетов аналитики
    mbh.analytics.types:
        sales_packages: "Динамика продаж по количеству броней"
        sales_cash: "Динамика продаж по стоимости броней"
        sales_cash_documents: "Динамика продаж в полученных деньгах"
        sales_sources: "Источники продаж"
        hotel_occupancy: "Заполняемость отеля"
        sales_services: "Динамика реализации услуг"
        sales_managers: "Менеджеры и брони"


    #Цели приезда
    mbh.package.arrivals:
        tourism: "Отдых/туризм"
        work: "Работа/стажировка"
        study: "Курсы/учеба"
        residence: "Временное проживание"
        other: "Другое"

    #Время заезда по умолчанию
    mbh.package.arrival.time: %mbh_package_arrival_time%
    
    #Просроченные брони
    mbh.package.notpaid.time: '%mbh_package_notpaid_time%'

    #Цели приезда
    mbh.package.statuses:
        offline: { title: "Обычная", class: "info", icon: "fa fa-paper-plane-o"}
        online: { title: "Онлайн", class: "success", icon: "fa fa-globe"}
        channel_manager: { title: "Channel manager", class: "danger", icon: "fa fa-cloud-download"}


    #Статусы задач
    mbh.task.statuses:
        process: { title: "В процессе", class: "info"}
        open: { title: "Открыта", class: "success"}
        closed: { title: "Закрыта", class: "danger"}

    #Типы документов
    mbh.order.document.types:
        passport: package.document.type_passport
        foreign_passport: package.document.type_foreign_passport
        insurance: package.document.type_insurance
        birth_certificate: package.document.type_birth_certificate
        military: package.document.type_military
        accommodation_voucher: package.document.type_accommodation_voucher
        shuttle_voucher: package.document.type_shuttle_voucher
        sertives_voucher: package.document.type_sertives_voucher
        complex: package.document.type_complex
        congirmation_account: package.document.type_congirmation_account
        invoice_for_payment: package.document.type_invoice_for_payment
        contract: package.document.type_contract
        extra_argument: package.document.type_extra_argument
        air_tickets: package.document.type_air_tickets
        train_tickets: package.document.type_train_tickets
        info: package.document.type_info
        letter: package.document.type_letter
        other: package.document.type_other

    #Виды способов оплаты
    mbh.cash.methods:
        cash: "Наличные"
        cashless: "Безнал"
        electronic: "Электронный"
    
    #Типы операций с кассой
    mbh.cash.operations:
        in: "Поступление"
        out: "Возврат"
        #fine: "Штраф"
        fee: "Комиссия"
        
    #Типы рассчета
    mbh.calculation.types:
        hotel:
          perRoom:      "Цена за номер"
          customPrices: "Цена за человека"
        hostel:
          perRoom:      "Цена за номер"
          customPrices: "Цена за койко-место"
        
    #Типы тарифов
    mbh.tariff.types:
        rate:      "Процент от цен основного тарифа"
        price:     "Индивидуальные цены"

    #М/Ж
    mbh.gender.types:
        male: "Мужчина"
        female: "Женщина"
        unknown: "Неизвестно"

    mbh.organization.types:
        contragents: 'Контрагенты'
        my: 'Мои организации'

    #Приоритет задач
    mbh.tasktype.priority:
        low: "Низкий"
        average: "Средний"
        high : "Высокий"