parameters:
    #генерация кеша
    mbh.room.cache.message: <i class="fa fa-spinner fa-spin"></i> Внимание! Идет пересчет цен и количества свободных номеров.
    mbh.room.cache.message.type: danger
    
    #параметры логов
    mbh.logs.max: 100
    
    #Типы питания
    mbh.food.types:
        RO:  "RO - Без питания"
        BB:  "BB - Завтрак"
        HB:  "HB - Завтрак и ужин"
        FB:  "FB - Завтрак, обед и ужин"
        AI:  "AI - Все включено"
        UAI: "UAI - Ультра все включено"
        
    #Типы рассчета
    mbh.calculation.types:
        perRoom:      "Цена за номер"
        customPrices: "Ручные цены"
        
    #Типы тарифов
    mbh.tariff.types:
        rate:      "Процент от цен основного тарифа"
        price:     "Конкретные цены"

    #М/Ж
    mbh.gender.types:
        male: "Мужчина"
        female: "Женщина"
        unknown: "Неизвестно"

    
    