parameters:

    mbh.channelmanager.services:
        vashotel:
          title: 'ВашОтель.RU'
          service: 'mbh.channelmanager.vashotel'
          password: jguuE26t684Fl
        booking:
          title: 'Booking.com'
          service: 'mbh.channelmanager.booking'
          username: maxibookingXML
          password: bMBhv6tds5i