security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN:
      - ROLE_HOTEL
      - ROLE_CITY

    #HOTEL
    ROLE_HOTEL: [ROLE_HOTEL_VIEW, ROLE_HOTEL_NEW, ROLE_HOTEL_EDIT1, ROLE_HOTEL_DELETE1]
    ROLE_CITY: [ROLE_CITY_VIEW, ROLE_CITY_NEW, ROLE_CITY_EDIT, ROLE_CITY_DELETE]