security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN:
      - ROLE_HOTEL
      - ROLE_GROUP
      - ROLE_CITY
      - ROLE_LOGS

    ROLE_LOGS: [ROLE_BASE_USER]
    ROLE_GROUP: [ROLE_GROUP_VIEW, ROLE_GROUP_NEW, ROLE_GROUP_EDIT, ROLE_GROUP_DELETE]
    ROLE_HOTEL: [ROLE_HOTEL_VIEW, ROLE_HOTEL_NEW, ROLE_HOTEL_EDIT, ROLE_HOTEL_DELETE]
    ROLE_CITY: [ROLE_CITY_VIEW]
