security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN:
      - ROLE_HOTEL
      - ROLE_GROUP
      - ROLE_CITY
      - ROLE_LOGS
      - ROLE_CASH
      - ROLE_BOOKKEEPER
      - ROLE_DOCUMENT_TEMPLATE

    ROLE_LOGS: [ROLE_BASE_USER]
    ROLE_GROUP: [ROLE_GROUP_VIEW, ROLE_GROUP_NEW, ROLE_GROUP_EDIT, ROLE_GROUP_DELETE]
    ROLE_HOTEL: [ROLE_HOTEL_VIEW, ROLE_HOTEL_NEW, ROLE_HOTEL_EDIT, ROLE_HOTEL_DELETE]
    ROLE_CITY: [ROLE_CITY_VIEW]
    ROLE_CASH: [ROLE_CASH_VIEW, ROLE_CASH_NEW, ROLE_CASH_EDIT, ROLE_CASH_DELETE]
    ROLE_BOOKKEEPER : [ROLE_CASH]
    ROLE_DOCUMENT_TEMPLATE: [ROLE_DOCUMENT_TEMPLATE_VIEW, ROLE_DOCUMENT_TEMPLATE_NEW, ROLE_DOCUMENT_TEMPLATE_EDIT, ROLE_DOCUMENT_TEMPLATE_DELETE]
