security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN:
      - ROLE_HOTEL
      - ROLE_CITY
      - ROLE_LOGS

    ROLE_LOGS: [ROLE_BASE_USER]
    ROLE_HOTEL: [ROLE_HOTEL_VIEW, ROLE_HOTEL_NEW, ROLE_HOTEL_EDIT, ROLE_HOTEL_DELETE]
    ROLE_CITY: [ROLE_CITY_VIEW]
