security:
  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    ROLE_ADMIN:
      - ROLE_HOTEL
      - ROLE_GROUP
      - ROLE_CITY
      - ROLE_LOGS
      - ROLE_CASH
      - ROLE_CLIENT_CONFIG
      - ROLE_DOCUMENT_TEMPLATE
      - ROLE_ROOM
      - ROLE_ROOM_TYPE
      - ROLE_TASK_MANAGER
      - ROLE_OVERVIEW
      - ROLE_PRICE_CACHE
      - ROLE_RESTRICTION
      - ROLE_ROOM_CACHE
      - ROLE_SERVICE
      - ROLE_SERVICE_CATEGORY
      - ROLE_TARIFF
      - ROLE_USER

    ROLE_LOGS: [ROLE_BASE_USER]
    ROLE_USER: [ROLE_USER_VIEW, ROLE_USER_NEW, ROLE_USER_EDIT, ROLE_USER_DELETE, ROLE_USER_PROFILE]
    ROLE_GROUP: [ROLE_GROUP_VIEW, ROLE_GROUP_NEW, ROLE_GROUP_EDIT, ROLE_GROUP_DELETE]
    ROLE_HOTEL: [ROLE_HOTEL_VIEW, ROLE_HOTEL_NEW, ROLE_HOTEL_EDIT, ROLE_HOTEL_DELETE]
    ROLE_CITY: [ROLE_CITY_VIEW]
    ROLE_CASH: [ROLE_CASH_VIEW, ROLE_CASH_NEW, ROLE_CASH_EDIT, ROLE_CASH_DELETE]
    ROLE_CLIENT_CONFIG: [ROLE_CLIENT_CONFIG_VIEW, ROLE_CLIENT_CONFIG_EDIT]
    ROLE_DOCUMENT_TEMPLATE: [ROLE_DOCUMENT_TEMPLATE_VIEW, ROLE_DOCUMENT_TEMPLATE_NEW, ROLE_DOCUMENT_TEMPLATE_EDIT, ROLE_DOCUMENT_TEMPLATE_DELETE]
    ROLE_ROOM_FUND: [ROLE_ROOM_TYPE, ROLE_ROOM]

    ROLE_HOUSING: [ROLE_HOUSING_VIEW, ROLE_HOUSING_NEW, ROLE_HOUSING_EDIT, ROLE_HOUSING_DELETE]

    ROLE_ROOM_TYPE: [ROLE_ROOM_TYPE_VIEW, ROLE_ROOM_TYPE_NEW, ROLE_ROOM_TYPE_EDIT, ROLE_ROOM_TYPE_DELETE]
    ROLE_ROOM: [ROLE_ROOM_VIEW, ROLE_ROOM_NEW, ROLE_ROOM_EDIT, ROLE_ROOM_DELETE]


    ROLE_TASK_MANAGER: [ROLE_TASK, ROLE_TASK_TYPE, ROLE_TASK_TYPE_CATEGORY]
    ROLE_TASK: [ROLE_TASK_VIEW, ROLE_TASK_NEW, ROLE_TASK_EDIT, ROLE_TASK_DELETE]
    ROLE_TASK_VIEW: [ROLE_TASK_OWN_VIEW]
    ROLE_TASK_TYPE: [ROLE_TASK_TYPE_VIEW, ROLE_TASK_TYPE_NEW, ROLE_TASK_TYPE_EDIT, ROLE_TASK_TYPE_DELETE]
    ROLE_TASK_TYPE_CATEGORY: [ROLE_TASK_TYPE_CATEGORY_VIEW, ROLE_TASK_TYPE_CATEGORY_NEW, ROLE_TASK_TYPE_CATEGORY_EDIT, ROLE_TASK_TYPE_CATEGORY_DELETE]

    ROLE_MANAGER: [ROLE_STAFF]
    ROLE_STAFF: [ROLE_TASK_OWN_VIEW]
    ROLE_PRICE_CACHE: [ROLE_PRICE_CACHE_VIEW, ROLE_PRICE_CACHE_EDIT]
    ROLE_RESTRICTION: [ROLE_RESTRICTION_VIEW, ROLE_RESTRICTION_EDIT]
    ROLE_ROOM_CACHE: [ROLE_ROOM_CACHE_VIEW, ROLE_ROOM_CACHE_EDIT]

    ROLE_SERVICE: [ROLE_SERVICE_VIEW, ROLE_SERVICE_NEW, ROLE_SERVICE_EDIT, ROLE_SERVICE_DELETE]
    ROLE_SERVICE_CATEGORY: [ROLE_SERVICE_CATEGORY_NEW, ROLE_SERVICE_CATEGORY_EDIT, ROLE_SERVICE_CATEGORY_DELETE]
    ROLE_TARIFF: [ROLE_TARIFF_VIEW, ROLE_TARIFF_NEW, ROLE_TARIFF_EDIT, ROLE_TARIFF_DELETE]