mbh_cash:
    resource: "@MBHCashBundle/Controller/"
    type:     annotation
    prefix:   /cash

_welcome:
    pattern:  /
    defaults: { _controller: MBHPackageBundle:Package:index}

mbh_package:
    resource: "@MBHPackageBundle/Controller/"
    type:     annotation
    prefix:   /package

mbh_price:
    resource: "@MBHPriceBundle/Controller/"
    type:     annotation
    prefix:   /management/price

mbh_base:
    resource: "@MBHBaseBundle/Controller/"
    type:     annotation
    prefix:   /base

mbh_user:
    resource: "@MBHUserBundle/Controller/"
    type:     annotation
    prefix:   /management/user
 
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /user
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

mbh_hotel:
    resource: "@MBHHotelBundle/Controller/"
    type:     annotation
    prefix:   /management/hotel


