mbh_base:
    resource: "@MBHBaseBundle/Controller/"
    type:     annotation
    prefix:   /

mbh_user:
    resource: "@MBHUserBundle/Controller/"
    type:     annotation
    prefix:   /management/user
 
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /user
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

mbh_hotel:
    resource: "@MBHHotelBundle/Controller/"
    type:     annotation
    prefix:   /management/hotel

_welcome:
    pattern:  /
    defaults: { _controller: MBHUserBundle:User:index}


