mbh_client:
    resource: "@MBHClientBundle/Controller/"
    type:     annotation
    prefix:   /management/client

mbh_online:
    resource: "@MBHOnlineBundle/Controller/"
    type:     annotation
    prefix:   /management/online

mbh_channel_manager:
    resource: "@MBHChannelManagerBundle/Controller/"
    type:     annotation
    prefix:   /management/channelmanager

mbh_cash:
    resource: "@MBHCashBundle/Controller/"
    type:     annotation
    prefix:   /cash

_welcome:
    pattern:  /
    defaults: { _controller: MBHPackageBundle:Package:index}

mbh_package:
    resource: "@MBHPackageBundle/Controller/"
    type:     annotation
    prefix:   /package


mbh_price:
    resource: "@MBHPriceBundle/Controller/"
    type:     annotation
    prefix:   /price

mbh_base:
    resource: "@MBHBaseBundle/Controller/"
    type:     annotation
    prefix:   /base

mbh_user:
    resource: "@MBHUserBundle/Controller/"
    type:     annotation
    prefix:   /
 
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /user
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

mbh_hotel:
    resource: "@MBHHotelBundle/Controller/"
    type:     annotation
    prefix:   /management/hotel

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

mdh_tasktype:
    resource: "@MBHHotelBundle/Controller/TaskTypeController.php"
    type:     annotation
    prefix:   /management/tasktype


mdh_task:
    resource: "@MBHHotelBundle/Controller/TaskController.php"
    type:     annotation
    prefix:   /management/task

