services:
    mbh.check_hotel.action_listener:
        class: MBH\Bundle\HotelBundle\EventListener\CheckHotelListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    mbh.hotel.task.subscriber:
        class: MBH\Bundle\HotelBundle\EventListener\TaskSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}
    mbh.hotel.facility.subscriber:
        class: MBH\Bundle\HotelBundle\EventListener\FacilitySubscriber
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}
    mbh.hotel.room_type.subscriber:
            class: MBH\Bundle\HotelBundle\EventListener\RoomTypeSubscriber
            tags:
                - { name: doctrine_mongodb.odm.event_subscriber, connection: default}
    mbh.hotel.auto_task_creator:
            class: MBH\Bundle\HotelBundle\Service\AutoTaskCreator
            arguments: [@service_container]

    mbh.hotel.room_type_manager:
                class: MBH\Bundle\HotelBundle\Service\RoomTypeManager
                arguments: [@service_container]

    mbh.hotel.console_auto_task_creator:
            class: MBH\Bundle\HotelBundle\Service\ConsoleAutoTaskCreator
            arguments: [@service_container]
    mbh.facility_repository:
        class: MBH\Bundle\HotelBundle\Document\FacilityRepository
        calls:
            - [ setContainer, [ '@service_container' ] ]

    mbh.hotel.task_repository:
        class: MBH\Bundle\HotelBundle\Document\TaskRepository
        factory_service: doctrine_mongodb.odm.default_document_manager
        factory_method: getRepository
        arguments:
            - MBH\Bundle\HotelBundle\Document\Task
        calls:
            - [ setContainer, [ '@service_container' ] ]

    mbh.hotel.hotel_manager:
        class: MBH\Bundle\HotelBundle\Service\HotelManager
        arguments: [@service_container]