services:
    mbh.check_hotel.action_listener:
        class: MBH\Bundle\HotelBundle\EventListener\CheckHotelListener
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    mbh.check_hotel.task_subscriber:
        class: MBH\Bundle\HotelBundle\EventListener\TaskSubscriber
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}
    mbh.check_hotel.hotel_subscriber:
        class: MBH\Bundle\HotelBundle\EventListener\HotelSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}