imports:
    - { resource: doctrine_extensions.yml }

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    doctrine_odm.mongodb.validator.unique:
      class: MBH\Bundle\BaseBundle\Validator\Constraints\UniqueEntityValidator
      arguments:
        - @doctrine_mongodb
      tags:
        - { name: validator.constraint_validator, alias: doctrine_odm.mongodb.unique }

    mbh.base_on_request_listener:
        class: MBH\Bundle\BaseBundle\EventListener\OnRequest
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    mbh.base_on_controller_listener:
        class: MBH\Bundle\BaseBundle\EventListener\OnController
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    mongodb_acl_provider:
            parent: doctrine_mongodb.odm.security.acl.provider

    mbh.twig.hotel_selector_extension:
        class: MBH\Bundle\BaseBundle\Twig\HotelSelectorExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    mbh.twig.plural_extension:
        class: MBH\Bundle\BaseBundle\Twig\PluralExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    mbh.twig.extension:
        class: MBH\Bundle\BaseBundle\Twig\Extension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
            
    mbh.form.fieldset_extension:
        class: MBH\Bundle\BaseBundle\Form\Extension\FieldsetExtension
        tags:
            - { name: form.type_extension, alias: form }
            
    mbh.form.help_extension:
        class: MBH\Bundle\BaseBundle\Form\Extension\HelpMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: form }

    form.type.date:
            class: MBH\Bundle\BaseBundle\Form\Extension\DateType
            tags:
                - { name: form.type, alias: date }
            
    mbh.form.bottom_extension:
        class: MBH\Bundle\BaseBundle\Form\Extension\BottomMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: form }
            
    mbh.hotel.selector:
        class: MBH\Bundle\BaseBundle\Service\HotelSelector
        arguments: [@service_container]

    mbh.currency:
            class: MBH\Bundle\BaseBundle\Service\Currency
            arguments: [@service_container]

    mbh.helper:
            class: MBH\Bundle\BaseBundle\Service\Helper
            arguments: [@service_container]

    mbh.pdf_generator:
        class: MBH\Bundle\BaseBundle\Service\PdfGenerator
        calls:
              - [ setContainer, [ '@service_container' ] ]

    mbh.mongo:
          class: MBH\Bundle\BaseBundle\Service\Mongo
          arguments: [@service_container]

    doctrine_mongo_db_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: [@doctrine_mongodb]
        tags:
          - { name: request.param_converter, converter: doctrine.odm }


    #Notifiers
    mbh.notifier:
      class: MBH\Bundle\BaseBundle\Service\Messenger\Notifier
      calls:
        - [attach, ["@mbh.system.messenger"]]
        - [attach, ["@mbh.mailer"]]
      arguments: [@service_container]

    mbh.notifier.mailer:
          class: MBH\Bundle\BaseBundle\Service\Messenger\Notifier
          calls:
            - [attach, ["@mbh.mailer"]]
          arguments: [@service_container]

    mbh.mailer:
      class: MBH\Bundle\BaseBundle\Service\Messenger\Mailer
      arguments: [@service_container]

    mbh.system.messenger:
      class: MBH\Bundle\BaseBundle\Service\Messenger\Messenger
      arguments: [@service_container]


    form.type.facilities:
        class: MBH\Bundle\BaseBundle\Form\FacilitiesType
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: form.type, alias: mbh_facilities }
    form.type.language:
        class: MBH\Bundle\BaseBundle\Form\LanguageType
        calls:
            - [ setContainer, [ '@service_container' ] ]
        tags:
            - { name: form.type, alias: mbh_language }


    #mbh.translatable_listener:
    #    class: MBH\Bundle\BaseBundle\EventListener\TranslatableListener
    #    calls:
    #          - [ setDefaultLocale, [ 'ru_RU' ] ]
    #          - [ setAnnotationReader, [ @annotation_reader ] ]
    #    tags:
    #          - { name: doctrine.event_subscriber, connection: default }

    mbh.event_listener.check_relation_subscriber:
        class: MBH\Bundle\BaseBundle\EventListener\CheckDeleteRelationSubscriber
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}
    mbh.event_listener.hotelable_listener:
        class: MBH\Bundle\BaseBundle\EventListener\HotelableListener
        arguments: [@mbh.hotel.selector]
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}
    mbh.get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }

    #mbh.menu.voter.request:
    #    class: MBH\Bundle\BaseBundle\Menu\RequestContentIdentityVoter
    #    arguments:
    #        - @service_container
    #    tags:
    #       - { name: knp_menu.voter }