services:
    doctrine_odm.mongodb.validator.unique:
      class: MBH\Bundle\BaseBundle\Validator\Constraints\UniqueEntityValidator
      arguments:
        - @doctrine_mongodb
      tags:
        - { name: validator.constraint_validator, alias: doctrine_odm.mongodb.unique }

    mbh.base_listener:
            class: MBH\Bundle\BaseBundle\EventListener\BaseListener
            arguments: [@service_container]
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    mongodb_acl_provider:
            parent: doctrine_mongodb.odm.security.acl.provider

    mbh.twig.hotel_selector_extension:
        class: MBH\Bundle\BaseBundle\Twig\HotelSelectorExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    mbh.twig.plural_extension:
            class: MBH\Bundle\BaseBundle\Twig\PluralExtension
            arguments: [@service_container]
            tags:
                - { name: twig.extension }

    mbh.twig.extension:
                class: MBH\Bundle\BaseBundle\Twig\Extension
                arguments: [@service_container]
                tags:
                    - { name: twig.extension }
            
    mbh.form.fieldset_extension:
        class: MBH\Bundle\BaseBundle\Form\Extension\FieldsetExtension
        tags:
            - { name: form.type_extension, alias: form }
            
    mbh.form.help_extension:
        class: MBH\Bundle\BaseBundle\Form\Extension\HelpMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: form }

    form.type.date:
            class: MBH\Bundle\BaseBundle\Form\Extension\DateType
            tags:
                - { name: form.type, alias: date }
            
    mbh.form.bottom_extension:
        class: MBH\Bundle\BaseBundle\Form\Extension\BottomMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: form }
            
    mbh.hotel.selector:
        class: MBH\Bundle\BaseBundle\Service\HotelSelector
        arguments: [@service_container]

    mbh.helper:
            class: MBH\Bundle\BaseBundle\Service\Helper

    mbh.mailer:
            class: MBH\Bundle\BaseBundle\Service\Mailer
            arguments: [@service_container]

    doctrine_mongo_db_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: [@doctrine_mongodb]
        tags:
          - { name: request.param_converter, converter: doctrine.odm }
