services:
    mbh.twig.hotel_selector_extension:
        class: MBH\Bundle\BaseBundle\Twig\HotelSelectorExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    mbh.twig.plural_extension:
            class: MBH\Bundle\BaseBundle\Twig\PluralExtension
            arguments: [@service_container]
            tags:
                - { name: twig.extension }
            
    mbh.form.fieldset_extension:
        class: MBH\Bundle\BaseBundle\Form\Extension\FieldsetExtension
        tags:
            - { name: form.type_extension, alias: form }
            
    mbh.form.help_extension:
        class: MBH\Bundle\BaseBundle\Form\Extension\HelpMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: form }
            
    mbh.form.bottom_extension:
        class: MBH\Bundle\BaseBundle\Form\Extension\BottomMessageTypeExtension
        tags:
            - { name: form.type_extension, alias: form }
            
    mbh.hotel.selector:
        class: MBH\Bundle\BaseBundle\Service\HotelSelector
        arguments: [@service_container]

    mbh.helper:
            class: MBH\Bundle\BaseBundle\Service\Helper

    mbh.mailer:
            class: MBH\Bundle\BaseBundle\Service\Mailer
            arguments: [@service_container]

    doctrine_mongo_db_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: [@doctrine_mongodb]
        tags:
          - { name: request.param_converter, converter: doctrine.odm }
