services:
    mbh.twig.hotel_selector_extension:
        class: MBH\Bundle\BaseBundle\Twig\HotelSelectorExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
