###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

mbh-memcached:
  image: phpdockerio/memcached:latest
  container_name: mbh-memcached

mbh-rabbitmq:
  image: rabbitmq:latest
  container_name: mbh-rabbitmq
  hostname: "mbh-rabbitmq"
  environment:
    RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
    RABBITMQ_DEFAULT_USER: "rabbitmq"
    RABBITMQ_DEFAULT_PASS: "rabbitmq"
    RABBITMQ_DEFAULT_VHOST: "/"
  ports:
    - "15672:15672"
    - "5672:5672"
  labels:
    NAME: "mbh-rabbitmq"
  volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"

mbh-mongo:
  image: mongo:latest
  container_name: mbh-mongo
  ports:
     - "27018:27017"

mbh-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: mbh-php-fpm
  volumes:
    - ..:/var/www/mbh
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/cli/conf.d/99-overrides.ini
    - ./php-fpm/start.sh:/start.sh
    - /tmp/:/tmp/
    - ./supervisor/:/etc/supervisor/conf.d/
  links:
    - mbh-memcached
    - mbh-mongo
    - mbh-rabbitmq

mbh-webserver:
  image: phpdockerio/nginx:latest
  container_name: mbh-webserver
  volumes:
      - ..:/var/www/mbh
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "9090:80"
  links:
   - mbh-php-fpm