services:
  mbh__restaurant.form_dish_order.dish_order_item_emmbedded_type:
      class: MBH\Bundle\RestaurantBundle\Form\DishOrder\DishOrderItemEmmbeddedType
      arguments: ['@request_stack', '@mbh.hotel.selector', '@mbh.helper']
      tags:
          - { name: form.type, alias: mbh_bundle_restaurantbundle_dishorder_dishitemembedded_type }

  mbh__restaurant.form.dish_menu_ingredient_embedded_type:
      class: MBH\Bundle\RestaurantBundle\Form\DishMenuIngredientEmbeddedType
      arguments: ['@service_container']
      tags:
          - { name: form.type, alias: mbh_bundle_restaurantbundle_dishmenu_ingredientembedded_type }

  mbh__restaurant.form_dish_order.dish_order_item_type:
      class: MBH\Bundle\RestaurantBundle\Form\DishOrder\DishOrderItemType
      arguments: ['@service_container']
      tags:
          - { name: form.type, alias: mbh_bundle_restaurantbundle_dishorder_dishorderitem_type }