services:
  mbh.testaurant.subscriber:
    class: MBH\Bundle\RestaurantBundle\EventListener\RestaurantSubscriber
    arguments: ["@service_container"]
    tags:
      - { name: doctrine_mongodb.odm.event_subscriber, connection: default }
