parameters:
    online_booking:
          request_search_url: /assets/vendor/azovsky/azovsky.ru/services/mb-search/index.php
          payonlineurl: http://azovsky-billing.com/pay/

    online_reservation_manager_email: "zalex@zalex.com.ua"
