parameters:
    online_booking:
          request_search_url: '/mbresults.php'
          payonlineurl: http://azovsky-billing.com/pay/

    online_reservation_manager_email: "mail@azovsky.ru"
    offera: "https://yadi.sk/i/aSRIUwg0zjWVw"

