services:
#    mbh_online_booking.example:
#        class: MBH\Bundle\OnlineBookingBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    mbh.online.search_form:
        class: MBH\Bundle\OnlineBookingBundle\Form\SearchFormType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    mbh.sign_form:
        class: MBH\Bundle\OnlineBookingBundle\Form\SignType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    mbh.reservation_form:
        class: MBH\Bundle\OnlineBookingBundle\Form\ReservationType
        arguments: ["@service_container"]
        tags:
            - { name: form.type }

    mbh.online.chart.data.former:
        class: MBH\Bundle\OnlineBookingBundle\Service\ChartDataFormer
        arguments: ["@mbh.calculation"]

    mbh.online.left_sale.twig_extension:
        class: MBH\Bundle\OnlineBookingBundle\Twig\OnlineBookingExtension
        arguments: ["@doctrine_mongodb.odm.default_document_manager", "%online_left_rooms%"]
        public: false
        tags:
            - { name: twig.extension }

    mbh.online.special_data_preparer:
        class: MBH\Bundle\OnlineBookingBundle\Service\SpecialDataPreparer
        arguments: ['@doctrine.odm.mongodb.document_manager']

    mbh.online.search_form_data:
        class: MBH\Bundle\OnlineBookingBundle\Lib\OnlineSearchFormData
        arguments: ['@mbh.hotel.room_type_manager']

    mbh.online.abstract_result_generator:
        abstract: true
        class: MBH\Bundle\OnlineBookingBundle\Service\OnlineSearchHelper\AbstractResultGenerator
        arguments: ['@mbh.package.search']

    mbh.online.common_result_generator:
        parent: mbh.online.abstract_result_generator
        class: MBH\Bundle\OnlineBookingBundle\Service\OnlineSearchHelper\OnlineCommonResultGenerator

    mbh.online.search_helper:
        class: MBH\Bundle\OnlineBookingBundle\Service\OnlineSearchHelper\OnlineSearchHelper
        arguments: ['%online_booking%']
        calls:
            - [addGenerator, ['@mbh.online.common_result_generator']]