services:
    mbh.kernel_root_dir:
        class: 'mock_class'
        factory: ["@kernel", getRootDir]

    mbh.service.client_list_getter:
        class: MBH\Bundle\BillingBundle\Service\ClientListGetter
        arguments: ["@mbh.kernel_root_dir"]

    mbh.maintenance.manager:
        class: MBH\Bundle\BillingBundle\Lib\Maintenance\MaintenanceManager
        calls:
            - [addMaintenance, ['@mbh.parameters.maintenance']]
            - [addMaintenance, ['@mbh.nginx.maintenance']]
            - [addMaintenance, ['@mbh.mongo.maintenance']]

    mbh.maintenance.abstract:
        abstract: true
        public: false
        arguments: ["@service_container"]
        class: MBH\Bundle\BillingBundle\Lib\Maintenance\AbstractMaintenance

    mbh.parameters.maintenance:
        class: MBH\Bundle\BillingBundle\Lib\Maintenance\ParametersMaintenance
        parent: mbh.maintenance.abstract

    mbh.nginx.maintenance:
        class: MBH\Bundle\BillingBundle\Lib\Maintenance\NginxMaintenance
        parent: mbh.maintenance.abstract

    mbh.mongo.maintenance:
        arguments: ["@service_container", {sampleDbName: "%mongodb_database%"}]

        class: MBH\Bundle\BillingBundle\Lib\Maintenance\MongoMaintenance
