services:
    mbh.channelmanager:
        class: MBH\Bundle\ChannelManagerBundle\Services\ChannelManager
        arguments: [@service_container]

    mbh.channelmanager.vashotel:
            class: MBH\Bundle\ChannelManagerBundle\Services\Vashotel
            arguments: [@service_container]

    mbh.channelmanager.oktogo:
            class: MBH\Bundle\ChannelManagerBundle\Services\Oktogo
            arguments: [@service_container]

    mbh.channelmanager.booking:
                class: MBH\Bundle\ChannelManagerBundle\Services\Booking
                arguments: [@service_container]