services:
    mbh.channelmanager:
        class: MBH\Bundle\ChannelManagerBundle\Services\ChannelManager
        arguments: ['@service_container']

    mbh.channelmanager.vashotel:
        class: MBH\Bundle\ChannelManagerBundle\Services\Vashotel
        arguments: ['@service_container']

    mbh.channelmanager.oktogo:
        class: MBH\Bundle\ChannelManagerBundle\Services\Oktogo
        arguments: ['@service_container']

    mbh.channelmanager.booking:
        class: MBH\Bundle\ChannelManagerBundle\Services\Booking
        arguments: ['@service_container']

    mbh.channelmanager.myallocator:
        class: MBH\Bundle\ChannelManagerBundle\Services\MyAllocator
        arguments: ['@service_container']

    mbh.channelmanager.ostrovok:
        class: MBH\Bundle\ChannelManagerBundle\Services\Ostrovok
        arguments: ['@service_container']

    mbh.channelmanager.expedia:
        class: MBH\Bundle\ChannelManagerBundle\Services\Expedia\Expedia
        arguments: ['@service_container']

    mbh.channelmanager.expedia_type:
        class: MBH\Bundle\ChannelManagerBundle\Form\ExpediaType

    mbh.channelmanager.expedia_request_formatter:
        class: MBH\Bundle\ChannelManagerBundle\Services\Expedia\ExpediaRequestFormatter

    mbh.channelmanager.expedia_request_data_formatter:
        class: MBH\Bundle\ChannelManagerBundle\Services\Expedia\ExpediaRequestDataFormatter
        arguments: ['@service_container']

    mbh.channelmanager.helper:
        class: MBH\Bundle\ChannelManagerBundle\Services\ChannelManagerHelper
        arguments: ['@mbh.notifier', '@translator', '@doctrine_mongodb.odm.document_manager']

    mbh.channelmanager.expedia_response_handler:
        class: MBH\Bundle\ChannelManagerBundle\Services\Expedia\ExpediaResponseHandler
        arguments: ['@service_container']
        shared: false

    mbh.channelmanager.expedia_order_info:
        class: MBH\Bundle\ChannelManagerBundle\Services\Expedia\ExpediaOrderInfo
        arguments: ['@service_container']
        shared: false

    mbh.channelmanager.expedia_package_info:
        class: MBH\Bundle\ChannelManagerBundle\Services\Expedia\ExpediaPackageInfo
        arguments: ['@service_container']
        shared: false

    mbh.channelmanager.homeaway_data_formatter:
        class: MBH\Bundle\ChannelManagerBundle\Services\HomeAway\HomeAwayDataFormatter
        arguments: ['@doctrine.odm.mongodb.document_manager', '@mbh.hotel.room_type_manager', '@mbh.package.search']

    mbh.channelmanager.homeaway_response_compiler:
        class: MBH\Bundle\ChannelManagerBundle\Services\HomeAway\HomeAwayResponseCompiler
        arguments:
          - '@mbh.channelmanager.homeaway_data_formatter'
          - '%locale.currency%'
          - '@mbh.currency'
          - '@mbh.channelmanager.helper'
          - '@router'
          - '%home_away_assigned_id%'
          - '%router.request_context.host%'
          - '@doctrine_mongodb.odm.document_manager'

    mbh.channelmanager.homeaway_order_info:
        class: MBH\Bundle\ChannelManagerBundle\Services\HomeAway\HomeAwayOrderInfo
        arguments: ['@service_container']
        shared: false

    mbh.channelmanager.homeaway_package_info:
        class: MBH\Bundle\ChannelManagerBundle\Services\HomeAway\HomeAwayPackageInfo
        arguments: ['@service_container']
        shared: false

    mbh.channel_manager.order_handler:
        class: MBH\Bundle\ChannelManagerBundle\Services\OrderHandler
        arguments: ['@doctrine.odm.mongodb.document_manager', '@mbh.package.search', '@translator', '@validator']

    mbh.channelmanager.hundred_one_hotels:
        class: MBH\Bundle\ChannelManagerBundle\Services\HundredOneHotels
        arguments: ['@service_container']

    mbh.channelmanager.hoh_order_info:
        class: MBH\Bundle\ChannelManagerBundle\Model\HundredOneHotels\OrderInfo
        arguments: ['@service_container']
        shared: false

    mbh.channelmanager.hoh_package_info:
        class: MBH\Bundle\ChannelManagerBundle\Model\HundredOneHotels\PackageInfo
        arguments: ['@service_container']
        shared: false

    mbh.channelmanager.hoh_request_formatter:
        class: MBH\Bundle\ChannelManagerBundle\Model\HundredOneHotels\HOHRequestFormatter

    mbh.channelmanager.booking_type:
      class: MBH\Bundle\ChannelManagerBundle\Form\BookingType
      arguments: ['@mbh.currency']
      tags:
              - { name: form.type }

    mbh.channelmanager.myallocator_type:
      class: MBH\Bundle\ChannelManagerBundle\Form\MyallocatorType
      arguments: ['@mbh.channelmanager.myallocator', '@mbh.currency']
      tags:
              - { name: form.type }

    mbh.channelmanager.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, ['@mbh.channelmanager.logger_handler']]

    mbh.channelmanager.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: ['%kernel.logs_dir%/%kernel.environment%.channelmanager.log', 200]

    mbh.channelmanager.configs.subscriber:
            class: MBH\Bundle\ChannelManagerBundle\EventListener\ConfigsSubscriber
            arguments: ['@service_container']
            tags:
                - { name: doctrine_mongodb.odm.event_subscriber, connection: default}

    ostrovok_api_service:
        class: MBH\Bundle\ChannelManagerBundle\Lib\Ostrovok\OstrovokApiService
        arguments: ['%mbh.channelmanager.services%']

    mbh_bundle_channel_manager.lib_ostrovok.ostrovok_data_generator:
        class: MBH\Bundle\ChannelManagerBundle\Lib\Ostrovok\OstrovokDataGenerator

    mbh.channel_manager.trip_advisor_response_formatter:
      class: MBH\Bundle\ChannelManagerBundle\Services\TripAdvisor\TripAdvisorResponseFormatter
      arguments: ['%trip_advisor_confirmation_url%', '%router.request_context.host%', '%mbh_package_arrival_time%', '%mbh_package_departure_time%', '%online_form_result_url%', '%locale%', '@doctrine_mongodb.odm.document_manager', '@vich_uploader.templating.helper.uploader_helper', '@mbh.currency', '%locale.currency%', '@mbh.channel_manager.order_handler']

    mbh.channel_manager.trip_advisor_response_data_formatter:
      class: MBH\Bundle\ChannelManagerBundle\Services\TripAdvisor\TripAdvisorDataFormatter
      arguments: ['@mbh.package.search', '@doctrine.odm.mongodb.document_manager']

    mbh.channel_manager.trip_advisor_order_info:
      class: MBH\Bundle\ChannelManagerBundle\Services\TripAdvisor\TripAdvisorOrderInfo
      arguments: ['@service_container']
      shared: false

    mbh.channel_manager.trip_advisor_package_info:
      class: MBH\Bundle\ChannelManagerBundle\Services\TripAdvisor\TripAdvisorPackageInfo
      arguments: ['@service_container']
      shared: false

    mbh.channel_manager.trip_advisor.tariff_type:
      class: MBH\Bundle\ChannelManagerBundle\Form\TripAdvisor\TripAdvisorTariffType
      arguments: ['@doctrine.odm.mongodb.document_manager']
      tags:
          - { name: form.type }

    mbh.channel_manager.trip_advisor.tariffs_type:
      class: MBH\Bundle\ChannelManagerBundle\Form\TripAdvisor\TripAdvisorTariffsType
      tags:
          - { name: form.type }

    mbh.channelmanager.ostrovok.api_service:
        class: MBH\Bundle\ChannelManagerBundle\Lib\Ostrovok\OstrovokApiService
        arguments: ['%mbh.channelmanager.services%']

    mbh.channelmanager.ostrovok.data_generator:
        class: MBH\Bundle\ChannelManagerBundle\Lib\Ostrovok\OstrovokDataGenerator

    mbh.channelmanager.trip_advisor_fee_type:
        class: MBH\Bundle\ChannelManagerBundle\Form\TripAdvisor\TripAdvisorFeeType
        arguments: ['@mbh.currency']
        tags:
            - { name: form.type }

    mbh.channel_manager.trip_advisor_validator:
        class: MBH\Bundle\ChannelManagerBundle\Validator\Constraints\TripAdvisorValidator
        arguments: ['@translator']
        tags:
            - { name: validator.constraint_validator }

    mbh.channel_manager.home_away_validator:
        class: MBH\Bundle\ChannelManagerBundle\Validator\Constraints\HomeAwayValidator
        arguments: ['@mbh.channel_manager.home_away']
        tags:
            - {name: validator.constraint_validator}

    mbh.channel_manager.home_away:
        class: MBH\Bundle\ChannelManagerBundle\Services\HomeAway\HomeAway
        arguments: ['@translator', '%home_away_assigned_id%']