services:
    mbh.channelmanager:
        class: MBH\Bundle\ChannelManagerBundle\Services\ChannelManager
        arguments: [@service_container]

    mbh.channelmanager.vashotel:
            class: MBH\Bundle\ChannelManagerBundle\Services\Vashotel
            arguments: [@service_container]

    mbh.channelmanager.oktogo:
            class: MBH\Bundle\ChannelManagerBundle\Services\Oktogo
            arguments: [@service_container]

    mbh.channelmanager.booking:
                class: MBH\Bundle\ChannelManagerBundle\Services\Booking
                arguments: [@service_container]
                
    mbh.channelmanager.subscriber:
        class: MBH\Bundle\ChannelManagerBundle\EventListener\ChannelManagerSubscriber
        arguments: [@service_container]
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber, connection: default}

    mbh.channelmanager.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [app]
        calls:
            - [pushHandler, [@mbh.channelmanager.logger_handler]]

    mbh.channelmanager.logger_handler:
        class:     Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/%kernel.environment%.channelmanager.log, 200]