services:
#roomCache generator
  mbh.room.cache.graph.generator:
    class: MBH\Bundle\PriceBundle\Services\RoomCacheGraphGenerator
    arguments: ['@mbh.helper', '@doctrine_mongodb', '@service_container']

  mbh.tariff.subscriber:
    class: MBH\Bundle\PriceBundle\EventListener\TariffSubscriber
    arguments: ['@service_container']
    tags:
      - { name: doctrine_mongodb.odm.event_subscriber, connection: default}

  mbh.room_cache.subscriber:
      class: MBH\Bundle\PriceBundle\EventListener\RoomCacheSubscriber
      arguments: ['@service_container']
      tags:
        - { name: doctrine_mongodb.odm.event_subscriber, connection: default}

  mbh.room.cache:
          class: MBH\Bundle\PriceBundle\Services\RoomCache
          arguments: ['@service_container']

  mbh.price.cache:
          class: MBH\Bundle\PriceBundle\Services\PriceCache
          arguments: ['@service_container']

  mbh.restriction:
            class: MBH\Bundle\PriceBundle\Services\Restriction
            arguments: ['@service_container']

  task_room_cache_recalculate:
    class:      MBH\Bundle\PriceBundle\Task\RecalculateCache
    arguments:  ["@mbh.room.cache", "@mbh.task.logger"]

  mbh.type.special:
      class:      MBH\Bundle\PriceBundle\Form\SpecialType
      arguments:  ["@mbh.hotel.selector"]
      tags:
              - { name: form.type }

  mbh.type.special_filter:
        class:      MBH\Bundle\PriceBundle\Form\SpecialFilterType
        arguments:  ["@mbh.hotel.selector"]
        tags:
                - { name: form.type }

  mbh.type.tariff_filter:
        class:      MBH\Bundle\PriceBundle\Form\TariffFilterType
        arguments:  ["@mbh.hotel.selector"]
        tags:
                - { name: form.type }

  mbh.tariff_type:
      class: MBH\Bundle\PriceBundle\Form\TariffType
      arguments: ['@translator']
      tags:
          - {name : form.type}

  mbh.price_cache_generator_type:
      class: MBH\Bundle\PriceBundle\Form\PriceCacheGeneratorType
      arguments: ['@translator']
      tags:
          - {name: form.type}

  mbh.serice_category_type:
      class: MBH\Bundle\PriceBundle\Form\ServiceCategoryType
      arguments: ['@translator']
      tags:
          - {name: form.type}

  mbh.promotion_type:
      class: MBH\Bundle\PriceBundle\Form\PromotionType
      arguments: ['@translator']
      tags:
          - {name: form.type}

  mbh.tariff_services_type:
      class: MBH\Bundle\PriceBundle\Form\TariffServicesType
      arguments: ['@translator']
      tags:
          - {name: form.type}

  mbh.tariff_inheritance_type:
      class: MBH\Bundle\PriceBundle\Form\TariffInheritanceType
      arguments: ['@translator']
      tags:
          - {name: form.type}